server:
  port: 9411

spring:
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  application:
    name: zipkin-server
  rabbitmq: #配置mq消息队列
    host: mini7
    port: 5672
    username: root
    password: 123456

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: mini7
      #      username: elastic
      #      password: changeme
      cluster: cluster1
      index: zipkin
      index-shards: 1
      index-replicas: 1
      max-requests: 64
      port: 9200

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:12370/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false