spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:12382/
  sleuth:
    sampler:
      percentage: 1
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 12371

zuul:
  ratelimit:
    enabled: true
    repository: REDIS #使用redis存储，一定要大写！
    policies:
      test: #针对上面那个服务的限流
        limit: 1 #每秒多少个请求
        refreshInterval: 60
        type:
          - ORIGIN #这里一定要大写！
  routes:
    member:
      path: /member/**
      serviceId: member
    order:
      path: /order/**
      serviceId: order
    coupon:
      path: /coupon/**
      serviceId: coupon
    user:
      path: /user/**
      serviceId: user
    baseData:
      path: /baseData/**
      serviceId: baseData
      stripPrefix: false
    warehouse:
      path: /warehouse/**
      serviceId: warehouse
    collectCard:
      path: /collectCard/**
      serviceId: collectCard
    lottery:
      path: /lottery/**
      serviceId: lottery

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12370/eureka/

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #断路器超时时间，默认1000ms

token:
  exclude: /member/api/user/login

management:
  security:
    enabled: false
