spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:12370/
  sleuth:
    sampler:
      percentage: 1
server:
  port: 12371

zuul:
  routes:
    member:
      path: /member/**
      serviceId: member
    order:
      path: /order/**
      serviceId: order

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12370/eureka/