server:
  port: 12401
  context-path: /secKill

mysql:
  server:
    seckill:
      driverClassName: com.mysql.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8"
      username: root
      password: 123456
      maxActive: 50
      maxWait: 5000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true