server:
  port: 12388
spring:
  application:
    name: service-admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12370/eureka/
management:
  security:
    enabled: false
info:
  version: @project.version@